import storage_sql

db = storage_sql.DBController('storage', '0961533469Vi', 'root')
db.get_all_sections()
db.get_all_goods()
db.delete_goods(5)
db.get_all_goods()
db.get_all_goods_by_section(1)
db.add_goods(5, 3, 'Raffaello', 3, 'Chocolate')
db.get_all_goods()
db.delete_sections(1)
db.get_all_sections()
db.get_all_goods()
db.add_section(1, 'Food')
db.add_goods(1, 1, 'Apple', 1.35, 'Fruits')
db.add_goods(23, 1, 'Bananas', 3.50, 'Fruits')
db.get_all_sections()
db.get_all_goods()
db.edit_goods(23)
db.get_all_goods()
db.edit_section(1)
db.get_all_sections()
db.get_all_goods()
db.delete_sections(4)
db.get_all_sections()
db.get_all_goods()
db.add_section(1, 'Food')
db.add_goods(1, 1, 'Apple', 1.35, 'Fruits')
db.add_goods(2, 1, 'Bananas', 3.50, 'Fruits')
db.get_all_sections()
db.get_all_goods()
db.close_db()
