import storage_sql
import config

db = storage_sql.DBController(config.database_name, config.password, config.username)
db.get_all_sections()
db.get_all_goods()
print('#'*40)
db.delete_goods(5)
db.get_all_goods()
db.get_all_goods_by_section(1)
print('#'*40)
db.add_goods(5, 3, 'Raffaello', 3, 'Chocolate')
db.get_all_goods()
db.delete_sections(1)
db.get_all_sections()
db.get_all_goods()
print('#'*40)
db.add_section(1, 'Food')
db.add_goods(1, 1, 'Apple', 1.35, 'Fruits')
db.add_goods(23, 1, 'Bananas', 3.50, 'Fruits')
db.add_goods(6, 1, 'Orange', 0.99, 'Fruits')
db.add_goods(7, 1, 'Potato', 1.99, 'Vegetables')
db.get_all_sections()
db.get_all_goods()
print('#'*40)
db.edit_goods(23, 1, 2)
db.get_all_goods()
print('#'*40)
db.edit_section(1, 1, 4)
db.get_all_sections()
db.get_all_goods()
print('#'*40)
db.delete_sections(4)
db.get_all_sections()
db.get_all_goods()
print('#'*40)
db.add_section(1, 'Food')
db.add_goods(1, 1, 'Apple', 1.35, 'Fruits')
db.add_goods(2, 1, 'Bananas', 3.50, 'Fruits')
db.add_goods(6, 1, 'Orange', 0.99, 'Fruits')
db.add_goods(7, 1, 'Potato', 1.99, 'Vegetables')
db.get_all_sections()
db.get_all_goods()
db.close_db()
