# Generated by Django 4.0.3 on 2022-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_go', models.IntegerField(db_column='ID_GO')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=32, null=True)),
                ('price', models.FloatField(blank=True, db_column='PRICE', null=True)),
                ('goodstype', models.CharField(blank=True, db_column='GOODSTYPE', max_length=32, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id_se', models.IntegerField(db_column='ID_SE', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=32, null=True)),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
    ]
